# Generated by Django 4.1.5 on 2023-01-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('img2', models.ImageField(upload_to='', verbose_name='pics')),
                ('des', models.TextField()),
            ],
        ),
    ]
